module Questions
	ALL = [
	 {category: :extraversion, value: "1", question: "I am the life of the party."},
	 {category: :agreeableness, value: "-1", question: "I insult people."},
	 {category: :conscientiousness, value: "1", question: "I am always prepared."},
	 {category: :emotional_stability, value: "-1", question: "I get stressed out easily."},
	 {category: :intellect_imagination, value: "1", question: "I have a rich vocabulary."},
	 {category: :extraversion, value: "-1", question: "I often feel uncomfortable around others."},
	 {category: :agreeableness, value: "1", question: "I am interested in people."},
	 {category: :conscientiousness, value: "-1", question: "I leave my belongings around."},
	 {category: :emotional_stability, value: "1", question: "I am relaxed most of the time."},
	 {category: :intellect_imagination, value: "-1", question: "I have difficulty understanding abstract ideas."},
	 {category: :extraversion, value: "1", question: "I feel comfortable around people."},
	 {category: :agreeableness, value: "-1", question: "I am not interested in other people's problems."},
	 {category: :conscientiousness, value: "1", question: "I pay attention to details."},
	 {category: :emotional_stability, value: "-1", question: "I worry about things."},
	 {category: :intellect_imagination, value: "1", question: "I have a vivid imagination."},
	 {category: :extraversion, value: "-1", question: "I keep in the background."},
	 {category: :agreeableness, value: "1", question: "I sympathize with others' feelings."},
	 {category: :conscientiousness, value: "-1", question: "I make a mess of things."},
	 {category: :emotional_stability, value: "1", question: "I seldom feel blue."},
	 {category: :intellect_imagination, value: "-1", question: "I am not interested in abstract ideas."},
	 {category: :extraversion, value: "1", question: "I start conversations."},
	 {category: :agreeableness, value: "-1", question: "I feel little concern for others."},
	 {category: :conscientiousness, value: "1", question: "I get chores done right away."},
	 {category: :emotional_stability, value: "-1", question: "I am easily disturbed."},
	 {category: :intellect_imagination, value: "1", question: "I have excellent ideas."},
	 {category: :extraversion, value: "-1", question: "I have little to say."},
	 {category: :agreeableness, value: "1", question: "I have a soft heart."},
	 {category: :conscientiousness, value: "-1", question: "I often forget to put things back in their proper place."},
	 {category: :emotional_stability, value: "1", question: "I am not easily bothered by things."},
	 {category: :intellect_imagination, value: "-1", question: "I do not have a good imagination."},
	 {category: :extraversion, value: "1", question: "I talk to a lot of different people at parties."},
	 {category: :agreeableness, value: "-1", question: "I am not really interested in others."},
	 {category: :conscientiousness, value: "1", question: "I like order."},
	 {category: :emotional_stability, value: "-1", question: "I get upset easily."},
	 {category: :intellect_imagination, value: "1", question: "I am quick to understand things."},
	 {category: :extraversion, value: "-1", question: "I don't like to draw attention to myself."},
	 {category: :agreeableness, value: "1", question: "I take time out for others."},
	 {category: :conscientiousness, value: "-1", question: "I shirk my duties."},
	 {category: :emotional_stability, value: "1", question: "I rarely get irritated."},
	 {category: :intellect_imagination, value: "-1", question: "I try to avoid complex people."},
	 {category: :extraversion, value: "1", question: "I don't mind being the center of attention."},
	 {category: :agreeableness, value: "-1", question: "I am hard to get to know."},
	 {category: :conscientiousness, value: "1", question: "I follow a schedule."},
	 {category: :emotional_stability, value: "-1", question: "I change my mood a lot."},
	 {category: :intellect_imagination, value: "1", question: "I use difficult words."},
	 {category: :extraversion, value: "-1", question: "I am quiet around strangers."},
	 {category: :agreeableness, value: "1", question: "I feel others' emotions."},
	 {category: :conscientiousness, value: "-1", question: "I neglect my duties."},
	 {category: :emotional_stability, value: "1", question: "I seldom get mad."},
	 {category: :intellect_imagination, value: "-1", question: "I have difficulty imagining things."},
	 {category: :extraversion, value: "1", question: "I make friends easily."},
	 {category: :agreeableness, value: "-1", question: "I am indifferent to the feelings of others."},
	 {category: :conscientiousness, value: "1", question: "I am exacting in my work."},
	 {category: :emotional_stability, value: "-1", question: "I have frequent mood swings."},
	 {category: :intellect_imagination, value: "1", question: "I spend time reflecting on things."},
	 {category: :extraversion, value: "-1", question: "I find it difficult to approach others."},
	 {category: :agreeableness, value: "1", question: "I make people feel at ease."},
	 {category: :conscientiousness, value: "-1", question: "I waste my time."},
	 {category: :emotional_stability, value: "-1", question: "I get irritated easily."},
	 {category: :intellect_imagination, value: "-1", question: "I avoid difficult reading material."},
	 {category: :extraversion, value: "1", question: "I take charge."},
	 {category: :agreeableness, value: "1", question: "I inquire about others' well-being."},
	 {category: :conscientiousness, value: "1", question: "I do things according to a plan."},
	 {category: :emotional_stability, value: "-1", question: "I often feel blue."},
	 {category: :intellect_imagination, value: "1", question: "I am full of ideas."},
	 {category: :extraversion, value: "-1", question: "I don't talk a lot."},
	 {category: :agreeableness, value: "1", question: "I know how to comfort others."},
	 {category: :conscientiousness, value: "-1", question: "I do things in a half-way manner."},
	 {category: :emotional_stability, value: "-1", question: "I get angry easily."},
	 {category: :intellect_imagination, value: "-1", question: "I will not probe deeply into a subject."},
	 {category: :extraversion, value: "1", question: "I know how to captivate people."},
	 {category: :agreeableness, value: "1", question: "I love children."},
	 {category: :conscientiousness, value: "1", question: "I continue until everything is perfect."},
	 {category: :emotional_stability, value: "-1", question: "I panic easily."},
	 {category: :intellect_imagination, value: "1", question: "I carry the conversation to a higher level."},
	 {category: :extraversion, value: "-1", question: "I bottle up my feelings."},
	 {category: :agreeableness, value: "1", question: "I am on good terms with nearly everyone."},
	 {category: :conscientiousness, value: "-1", question: "I find it difficult to get down to work."},
	 {category: :emotional_stability, value: "-1", question: "I feel threatened easily."},
	 {category: :intellect_imagination, value: "1", question: "I catch on to things quickly."},
	 {category: :extraversion, value: "1", question: "I feel at ease with people."},
	 {category: :agreeableness, value: "1", question: "I have a good word for everyone."},
	 {category: :conscientiousness, value: "1", question: "I make plans and stick to them."},
	 {category: :emotional_stability, value: "-1", question: "I get overwhelmed by emotions."},
	 {category: :intellect_imagination, value: "1", question: "I can handle a lot of information."},
	 {category: :extraversion, value: "-1", question: "I am a very private person."},
	 {category: :agreeableness, value: "1", question: "I show my gratitude."},
	 {category: :conscientiousness, value: "-1", question: "I leave a mess in my room."},
	 {category: :emotional_stability, value: "-1", question: "I take offense easily."},
	 {category: :intellect_imagination, value: "1", question: "I am good at many things."},
	 {category: :extraversion, value: "-1", question: "I wait for others to lead the way."},
	 {category: :agreeableness, value: "1", question: "I think of others first."},
	 {category: :conscientiousness, value: "1", question: "I love order and regularity."},
	 {category: :emotional_stability, value: "-1", question: "I get caught up in my problems."},
	 {category: :intellect_imagination, value: "1", question: "I love to read challenging material."},
	 {category: :extraversion, value: "1", question: "I am skilled in handling social situations."},
	 {category: :agreeableness, value: "1", question: "I love to help others."},
	 {category: :conscientiousness, value: "1", question: "I like to tidy up."},
	 {category: :emotional_stability, value: "-1", question: "I grumble about things."},
	 {category: :intellect_imagination, value: "1", question: "I love to think up new ways of doing things."}
	]
end